# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# PROFIL
adrien_profile = Profile.create(first_name: "Adrien", last_name: "Cassan")
adrien_user = User.create(email: "adrien.cassan@gmail.com", password: "password", profile: adrien_profile)


clement_profile = Profile.create(first_name: "Clement", last_name: "Larraufie")
clement_user = User.create(email: "clement.larraufie@hotmail.fr", password: "password", profile: clement_profile)


# Stock
Stock.create(name: "3m")
Stock.create(name: "Ab inbev")
Stock.create(name: "ABB")
Stock.create(name: "Abeo")
Stock.create(name: "Actia group")
Stock.create(name: "Alphabet")
Stock.create(name: "Argan")
Stock.create(name: "At&t")
Stock.create(name: "Axel springer")
Stock.create(name: "Balyo")
Stock.create(name: "Bnp paribas")
Stock.create(name: "Cemex")
Stock.create(name: "Coca-cola company")
Stock.create(name: "Cronos group")
Stock.create(name: "Danone")
Stock.create(name: "Ekinops")
Stock.create(name: "Eos imaging")
Stock.create(name: "Eutelsat")
Stock.create(name: "Fanuc corp")
Stock.create(name: "Figeac aero")
Stock.create(name: "Gascogne")
Stock.create(name: "Gladstone investment")
Stock.create(name: "Grupo aeroportuario del norte")
Stock.create(name: "Grupo bimbo")
Stock.create(name: "Invesco kbwy")
Stock.create(name: "Ishr jpmorgan eemb")
Stock.create(name: "Korian")
Stock.create(name: "KPN")
Stock.create(name: "Leonardo")
Stock.create(name: "Ltc properties")
Stock.create(name: "Lvmh")
Stock.create(name: "Match group")
Stock.create(name: "Mcdonald's")
Stock.create(name: "Orange")
Stock.create(name: "Procter & gamble")
Stock.create(name: "Realty income")
Stock.create(name: "Renault")
Stock.create(name: "Royal caribbean cruises")
Stock.create(name: "Sanofi")
Stock.create(name: "Siemens")
Stock.create(name: "Sopra Steria")
Stock.create(name: "Stmicroelectronics")
Stock.create(name: "Suez environnement")
Stock.create(name: "Tencent hldgs")
Stock.create(name: "Teradata corp")
Stock.create(name: "Total")
Stock.create(name: "United technologies")
Stock.create(name: "Valeo")
Stock.create(name: "Virbac")
Stock.create(name: "Walt Disney")
Stock.create(name: "Johnson & Johnson")
Stock.create(name: "Apple")
Stock.create(name: "Aviation latecoere")
Stock.create(name: "Bic")
Stock.create(name: "Carrefour")
Stock.create(name: "Cerinnov group")
Stock.create(name: "General electric")
Stock.create(name: "General mills")
Stock.create(name: "Iliad")
Stock.create(name: "Irobot")
Stock.create(name: "Ishares world iwrd")
Stock.create(name: "Kion group")
Stock.create(name: "Lowe's companie")
Stock.create(name: "Mcphy energy")
Stock.create(name: "Navya prom")
Stock.create(name: "Netflix")
Stock.create(name: "New senior investment group")
Stock.create(name: "Tableau software")
Stock.create(name: "Tesla")
