# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# PROFIL
adrien_profile = Profile.create(first_name: "Adrien", last_name: "Cassan")
adrien_user = User.create(email: "adrien.cassan@gmail.com", password: "password", profile: adrien_profile)


clement_profile = Profile.create(first_name: "Clement", last_name: "Larraufie")
clement_user = User.create(email: "clement.larraufie@hotmail.fr", password: "password", profile: clement_profile)


# Stock
Stock.create(name: "3m")
Stock.create(name: "Ab inbev")
Stock.create(name: "ABB")
Stock.create(name: "Abeo")
Stock.create(name: "Actia group")
Stock.create(name: "Alphabet")
Stock.create(name: "Argan")
Stock.create(name: "At&t")
Stock.create(name: "Axel springer")
Stock.create(name: "Balyo")
Stock.create(name: "Bnp paribas")
Stock.create(name: "Cemex")
Stock.create(name: "Coca-cola company")
Stock.create(name: "Cronos group")
Stock.create(name: "Danone")
Stock.create(name: "Ekinops")
Stock.create(name: "Eos imaging")
Stock.create(name: "Eutelsat")
Stock.create(name: "Fanuc corp")
Stock.create(name: "Figeac aero")
Stock.create(name: "Gascogne")
Stock.create(name: "Gladstone investment")
Stock.create(name: "Grupo aeroportuario del norte")
Stock.create(name: "Grupo bimbo")
Stock.create(name: "Invesco kbwy")
Stock.create(name: "Ishr jpmorgan eemb")
Stock.create(name: "Korian")
Stock.create(name: "KPN")
Stock.create(name: "Leonardo")
Stock.create(name: "Ltc properties")
Stock.create(name: "Lvmh")
Stock.create(name: "Match group")
Stock.create(name: "Mcdonald's")
Stock.create(name: "Orange")
Stock.create(name: "Procter & gamble")
Stock.create(name: "Realty income")
Stock.create(name: "Renault")
Stock.create(name: "Royal caribbean cruises")
Stock.create(name: "Sanofi")
Stock.create(name: "Siemens")
Stock.create(name: "Sopra Steria")
Stock.create(name: "Stmicroelectronics")
Stock.create(name: "Suez environnement")
Stock.create(name: "Tencent hldgs")
Stock.create(name: "Teradata corp")
Stock.create(name: "Total")
Stock.create(name: "United technologies")
Stock.create(name: "Valeo")
Stock.create(name: "Virbac")
Stock.create(name: "Walt Disney")
Stock.create(name: "Johnson & Johnson")
Stock.create(name: "Apple")
Stock.create(name: "Aviation latecoere")
Stock.create(name: "Bic")
Stock.create(name: "Carrefour")
Stock.create(name: "Cerinnov group")
Stock.create(name: "General electric")
Stock.create(name: "General mills")
Stock.create(name: "Iliad")
Stock.create(name: "Irobot")
Stock.create(name: "Ishares world iwrd")
Stock.create(name: "Kion group")
Stock.create(name: "Lowe's companie")
Stock.create(name: "Mcphy energy")
Stock.create(name: "Navya prom")
Stock.create(name: "Netflix")
Stock.create(name: "New senior investment group")
Stock.create(name: "Tableau software")
Stock.create(name: "Tesla")


# Analyse
StockRating.create(stock_id: 1, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 2, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 3, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 4, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 5, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 6, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 7, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 8, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 9, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 10, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 11, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 12, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 13, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 14, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 15, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 16, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 17, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 18, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 19, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 20, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 21, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 22, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 23, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 24, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 25, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 26, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 27, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 28, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 29, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 30, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 31, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 32, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 33, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 34, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 35, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 36, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 37, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 38, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 39, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 40, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 41, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 42, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 43, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 44, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 45, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 46, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 47, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 48, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 49, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 50, profile_id: 2, value: 'Buy')
StockRating.create(stock_id: 51, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 52, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 53, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 54, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 55, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 56, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 57, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 58, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 59, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 60, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 61, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 62, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 63, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 64, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 65, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 66, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 67, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 68, profile_id: 2, value: 'Neutral')
StockRating.create(stock_id: 69, profile_id: 2, value: 'Neutral')
